package com.bluto.fc.model;

import java.io.Serializable;

public class Agent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.AGENT_ID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Long AGENT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.AGENT_CODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String AGENT_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.NAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROVINCECODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Short PROVINCECODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DISTRICT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Short DISTRICT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.POST
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String POST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.TEL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String TEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FAX
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String FAX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.BIZREGISTER_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String BIZREGISTER_NUM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.REGTYPE_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Short REGTYPE_NUM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.BIZEND_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer BIZEND_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.BIZREG_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer BIZREG_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.LEGALMANCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String LEGALMANCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.WORKSCOPE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String WORKSCOPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.REGADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String REGADR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.EMAIL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.BIZADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String BIZADR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DELEGATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String DELEGATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DLG_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String DLG_CALL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DLG_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String DLG_CARDNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DLG_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String DLG_CARDCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.CONTACTADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String CONTACTADR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.DLG_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String DLG_POSTCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY_CALL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY_CARDNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY_CARDCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY_CONTACT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY_CONTACT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.PROXY_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String PROXY_POSTCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FIRSTCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String FIRSTCENSOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FIRSTAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer FIRSTAUDITDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FIRSTMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String FIRSTMARK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FINALCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String FINALCENSOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FINALAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer FINALAUDITDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.FINALMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String FINALMARK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.STATUS
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Short STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.CREPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String CREPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.CREDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer CREDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.CRETIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer CRETIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.CREPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String CREPROID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UPDPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String UPDPERSON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UPDDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer UPDDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UPDTIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer UPDTIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UPDPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private String UPDPROID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENT.UPDCNT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private Integer UPDCNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.AGENT_ID
     *
     * @return the value of AGENT.AGENT_ID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Long getAGENT_ID() {
        return AGENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.AGENT_ID
     *
     * @param AGENT_ID the value for AGENT.AGENT_ID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setAGENT_ID(Long AGENT_ID) {
        this.AGENT_ID = AGENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.AGENT_CODE
     *
     * @return the value of AGENT.AGENT_CODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getAGENT_CODE() {
        return AGENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.AGENT_CODE
     *
     * @param AGENT_CODE the value for AGENT.AGENT_CODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setAGENT_CODE(String AGENT_CODE) {
        this.AGENT_CODE = AGENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.NAME
     *
     * @return the value of AGENT.NAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.NAME
     *
     * @param NAME the value for AGENT.NAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROVINCECODE
     *
     * @return the value of AGENT.PROVINCECODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Short getPROVINCECODE() {
        return PROVINCECODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROVINCECODE
     *
     * @param PROVINCECODE the value for AGENT.PROVINCECODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROVINCECODE(Short PROVINCECODE) {
        this.PROVINCECODE = PROVINCECODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DISTRICT
     *
     * @return the value of AGENT.DISTRICT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Short getDISTRICT() {
        return DISTRICT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DISTRICT
     *
     * @param DISTRICT the value for AGENT.DISTRICT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDISTRICT(Short DISTRICT) {
        this.DISTRICT = DISTRICT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.POST
     *
     * @return the value of AGENT.POST
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPOST() {
        return POST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.POST
     *
     * @param POST the value for AGENT.POST
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPOST(String POST) {
        this.POST = POST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.TEL
     *
     * @return the value of AGENT.TEL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getTEL() {
        return TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.TEL
     *
     * @param TEL the value for AGENT.TEL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setTEL(String TEL) {
        this.TEL = TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FAX
     *
     * @return the value of AGENT.FAX
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getFAX() {
        return FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FAX
     *
     * @param FAX the value for AGENT.FAX
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFAX(String FAX) {
        this.FAX = FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.BIZREGISTER_NUM
     *
     * @return the value of AGENT.BIZREGISTER_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getBIZREGISTER_NUM() {
        return BIZREGISTER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.BIZREGISTER_NUM
     *
     * @param BIZREGISTER_NUM the value for AGENT.BIZREGISTER_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setBIZREGISTER_NUM(String BIZREGISTER_NUM) {
        this.BIZREGISTER_NUM = BIZREGISTER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.REGTYPE_NUM
     *
     * @return the value of AGENT.REGTYPE_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Short getREGTYPE_NUM() {
        return REGTYPE_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.REGTYPE_NUM
     *
     * @param REGTYPE_NUM the value for AGENT.REGTYPE_NUM
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setREGTYPE_NUM(Short REGTYPE_NUM) {
        this.REGTYPE_NUM = REGTYPE_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.BIZEND_DATE
     *
     * @return the value of AGENT.BIZEND_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getBIZEND_DATE() {
        return BIZEND_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.BIZEND_DATE
     *
     * @param BIZEND_DATE the value for AGENT.BIZEND_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setBIZEND_DATE(Integer BIZEND_DATE) {
        this.BIZEND_DATE = BIZEND_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.BIZREG_DATE
     *
     * @return the value of AGENT.BIZREG_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getBIZREG_DATE() {
        return BIZREG_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.BIZREG_DATE
     *
     * @param BIZREG_DATE the value for AGENT.BIZREG_DATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setBIZREG_DATE(Integer BIZREG_DATE) {
        this.BIZREG_DATE = BIZREG_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.LEGALMANCODE
     *
     * @return the value of AGENT.LEGALMANCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getLEGALMANCODE() {
        return LEGALMANCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.LEGALMANCODE
     *
     * @param LEGALMANCODE the value for AGENT.LEGALMANCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setLEGALMANCODE(String LEGALMANCODE) {
        this.LEGALMANCODE = LEGALMANCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.WORKSCOPE
     *
     * @return the value of AGENT.WORKSCOPE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getWORKSCOPE() {
        return WORKSCOPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.WORKSCOPE
     *
     * @param WORKSCOPE the value for AGENT.WORKSCOPE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setWORKSCOPE(String WORKSCOPE) {
        this.WORKSCOPE = WORKSCOPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.REGADR
     *
     * @return the value of AGENT.REGADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getREGADR() {
        return REGADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.REGADR
     *
     * @param REGADR the value for AGENT.REGADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setREGADR(String REGADR) {
        this.REGADR = REGADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.EMAIL
     *
     * @return the value of AGENT.EMAIL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.EMAIL
     *
     * @param EMAIL the value for AGENT.EMAIL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.BIZADR
     *
     * @return the value of AGENT.BIZADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getBIZADR() {
        return BIZADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.BIZADR
     *
     * @param BIZADR the value for AGENT.BIZADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setBIZADR(String BIZADR) {
        this.BIZADR = BIZADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DELEGATE
     *
     * @return the value of AGENT.DELEGATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getDELEGATE() {
        return DELEGATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DELEGATE
     *
     * @param DELEGATE the value for AGENT.DELEGATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDELEGATE(String DELEGATE) {
        this.DELEGATE = DELEGATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DLG_CALL
     *
     * @return the value of AGENT.DLG_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getDLG_CALL() {
        return DLG_CALL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DLG_CALL
     *
     * @param DLG_CALL the value for AGENT.DLG_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDLG_CALL(String DLG_CALL) {
        this.DLG_CALL = DLG_CALL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DLG_CARDNAME
     *
     * @return the value of AGENT.DLG_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getDLG_CARDNAME() {
        return DLG_CARDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DLG_CARDNAME
     *
     * @param DLG_CARDNAME the value for AGENT.DLG_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDLG_CARDNAME(String DLG_CARDNAME) {
        this.DLG_CARDNAME = DLG_CARDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DLG_CARDCODE
     *
     * @return the value of AGENT.DLG_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getDLG_CARDCODE() {
        return DLG_CARDCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DLG_CARDCODE
     *
     * @param DLG_CARDCODE the value for AGENT.DLG_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDLG_CARDCODE(String DLG_CARDCODE) {
        this.DLG_CARDCODE = DLG_CARDCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.CONTACTADR
     *
     * @return the value of AGENT.CONTACTADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getCONTACTADR() {
        return CONTACTADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.CONTACTADR
     *
     * @param CONTACTADR the value for AGENT.CONTACTADR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setCONTACTADR(String CONTACTADR) {
        this.CONTACTADR = CONTACTADR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.DLG_POSTCODE
     *
     * @return the value of AGENT.DLG_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getDLG_POSTCODE() {
        return DLG_POSTCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.DLG_POSTCODE
     *
     * @param DLG_POSTCODE the value for AGENT.DLG_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setDLG_POSTCODE(String DLG_POSTCODE) {
        this.DLG_POSTCODE = DLG_POSTCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY
     *
     * @return the value of AGENT.PROXY
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY() {
        return PROXY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY
     *
     * @param PROXY the value for AGENT.PROXY
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY(String PROXY) {
        this.PROXY = PROXY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY_CALL
     *
     * @return the value of AGENT.PROXY_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY_CALL() {
        return PROXY_CALL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY_CALL
     *
     * @param PROXY_CALL the value for AGENT.PROXY_CALL
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY_CALL(String PROXY_CALL) {
        this.PROXY_CALL = PROXY_CALL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY_CARDNAME
     *
     * @return the value of AGENT.PROXY_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY_CARDNAME() {
        return PROXY_CARDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY_CARDNAME
     *
     * @param PROXY_CARDNAME the value for AGENT.PROXY_CARDNAME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY_CARDNAME(String PROXY_CARDNAME) {
        this.PROXY_CARDNAME = PROXY_CARDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY_CARDCODE
     *
     * @return the value of AGENT.PROXY_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY_CARDCODE() {
        return PROXY_CARDCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY_CARDCODE
     *
     * @param PROXY_CARDCODE the value for AGENT.PROXY_CARDCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY_CARDCODE(String PROXY_CARDCODE) {
        this.PROXY_CARDCODE = PROXY_CARDCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY_CONTACT
     *
     * @return the value of AGENT.PROXY_CONTACT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY_CONTACT() {
        return PROXY_CONTACT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY_CONTACT
     *
     * @param PROXY_CONTACT the value for AGENT.PROXY_CONTACT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY_CONTACT(String PROXY_CONTACT) {
        this.PROXY_CONTACT = PROXY_CONTACT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.PROXY_POSTCODE
     *
     * @return the value of AGENT.PROXY_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getPROXY_POSTCODE() {
        return PROXY_POSTCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.PROXY_POSTCODE
     *
     * @param PROXY_POSTCODE the value for AGENT.PROXY_POSTCODE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setPROXY_POSTCODE(String PROXY_POSTCODE) {
        this.PROXY_POSTCODE = PROXY_POSTCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FIRSTCENSOR
     *
     * @return the value of AGENT.FIRSTCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getFIRSTCENSOR() {
        return FIRSTCENSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FIRSTCENSOR
     *
     * @param FIRSTCENSOR the value for AGENT.FIRSTCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFIRSTCENSOR(String FIRSTCENSOR) {
        this.FIRSTCENSOR = FIRSTCENSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FIRSTAUDITDATE
     *
     * @return the value of AGENT.FIRSTAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getFIRSTAUDITDATE() {
        return FIRSTAUDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FIRSTAUDITDATE
     *
     * @param FIRSTAUDITDATE the value for AGENT.FIRSTAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFIRSTAUDITDATE(Integer FIRSTAUDITDATE) {
        this.FIRSTAUDITDATE = FIRSTAUDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FIRSTMARK
     *
     * @return the value of AGENT.FIRSTMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getFIRSTMARK() {
        return FIRSTMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FIRSTMARK
     *
     * @param FIRSTMARK the value for AGENT.FIRSTMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFIRSTMARK(String FIRSTMARK) {
        this.FIRSTMARK = FIRSTMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FINALCENSOR
     *
     * @return the value of AGENT.FINALCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getFINALCENSOR() {
        return FINALCENSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FINALCENSOR
     *
     * @param FINALCENSOR the value for AGENT.FINALCENSOR
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFINALCENSOR(String FINALCENSOR) {
        this.FINALCENSOR = FINALCENSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FINALAUDITDATE
     *
     * @return the value of AGENT.FINALAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getFINALAUDITDATE() {
        return FINALAUDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FINALAUDITDATE
     *
     * @param FINALAUDITDATE the value for AGENT.FINALAUDITDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFINALAUDITDATE(Integer FINALAUDITDATE) {
        this.FINALAUDITDATE = FINALAUDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.FINALMARK
     *
     * @return the value of AGENT.FINALMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getFINALMARK() {
        return FINALMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.FINALMARK
     *
     * @param FINALMARK the value for AGENT.FINALMARK
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setFINALMARK(String FINALMARK) {
        this.FINALMARK = FINALMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.STATUS
     *
     * @return the value of AGENT.STATUS
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Short getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.STATUS
     *
     * @param STATUS the value for AGENT.STATUS
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setSTATUS(Short STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.CREPERSON
     *
     * @return the value of AGENT.CREPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getCREPERSON() {
        return CREPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.CREPERSON
     *
     * @param CREPERSON the value for AGENT.CREPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setCREPERSON(String CREPERSON) {
        this.CREPERSON = CREPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.CREDATE
     *
     * @return the value of AGENT.CREDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getCREDATE() {
        return CREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.CREDATE
     *
     * @param CREDATE the value for AGENT.CREDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setCREDATE(Integer CREDATE) {
        this.CREDATE = CREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.CRETIME
     *
     * @return the value of AGENT.CRETIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getCRETIME() {
        return CRETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.CRETIME
     *
     * @param CRETIME the value for AGENT.CRETIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setCRETIME(Integer CRETIME) {
        this.CRETIME = CRETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.CREPROID
     *
     * @return the value of AGENT.CREPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getCREPROID() {
        return CREPROID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.CREPROID
     *
     * @param CREPROID the value for AGENT.CREPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setCREPROID(String CREPROID) {
        this.CREPROID = CREPROID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UPDPERSON
     *
     * @return the value of AGENT.UPDPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getUPDPERSON() {
        return UPDPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UPDPERSON
     *
     * @param UPDPERSON the value for AGENT.UPDPERSON
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setUPDPERSON(String UPDPERSON) {
        this.UPDPERSON = UPDPERSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UPDDATE
     *
     * @return the value of AGENT.UPDDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getUPDDATE() {
        return UPDDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UPDDATE
     *
     * @param UPDDATE the value for AGENT.UPDDATE
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setUPDDATE(Integer UPDDATE) {
        this.UPDDATE = UPDDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UPDTIME
     *
     * @return the value of AGENT.UPDTIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getUPDTIME() {
        return UPDTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UPDTIME
     *
     * @param UPDTIME the value for AGENT.UPDTIME
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setUPDTIME(Integer UPDTIME) {
        this.UPDTIME = UPDTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UPDPROID
     *
     * @return the value of AGENT.UPDPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public String getUPDPROID() {
        return UPDPROID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UPDPROID
     *
     * @param UPDPROID the value for AGENT.UPDPROID
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setUPDPROID(String UPDPROID) {
        this.UPDPROID = UPDPROID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENT.UPDCNT
     *
     * @return the value of AGENT.UPDCNT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public Integer getUPDCNT() {
        return UPDCNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENT.UPDCNT
     *
     * @param UPDCNT the value for AGENT.UPDCNT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    public void setUPDCNT(Integer UPDCNT) {
        this.UPDCNT = UPDCNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENT
     *
     * @mbggenerated Thu Apr 30 11:12:19 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", AGENT_ID=").append(AGENT_ID);
        sb.append(", AGENT_CODE=").append(AGENT_CODE);
        sb.append(", NAME=").append(NAME);
        sb.append(", PROVINCECODE=").append(PROVINCECODE);
        sb.append(", DISTRICT=").append(DISTRICT);
        sb.append(", POST=").append(POST);
        sb.append(", TEL=").append(TEL);
        sb.append(", FAX=").append(FAX);
        sb.append(", BIZREGISTER_NUM=").append(BIZREGISTER_NUM);
        sb.append(", REGTYPE_NUM=").append(REGTYPE_NUM);
        sb.append(", BIZEND_DATE=").append(BIZEND_DATE);
        sb.append(", BIZREG_DATE=").append(BIZREG_DATE);
        sb.append(", LEGALMANCODE=").append(LEGALMANCODE);
        sb.append(", WORKSCOPE=").append(WORKSCOPE);
        sb.append(", REGADR=").append(REGADR);
        sb.append(", EMAIL=").append(EMAIL);
        sb.append(", BIZADR=").append(BIZADR);
        sb.append(", DELEGATE=").append(DELEGATE);
        sb.append(", DLG_CALL=").append(DLG_CALL);
        sb.append(", DLG_CARDNAME=").append(DLG_CARDNAME);
        sb.append(", DLG_CARDCODE=").append(DLG_CARDCODE);
        sb.append(", CONTACTADR=").append(CONTACTADR);
        sb.append(", DLG_POSTCODE=").append(DLG_POSTCODE);
        sb.append(", PROXY=").append(PROXY);
        sb.append(", PROXY_CALL=").append(PROXY_CALL);
        sb.append(", PROXY_CARDNAME=").append(PROXY_CARDNAME);
        sb.append(", PROXY_CARDCODE=").append(PROXY_CARDCODE);
        sb.append(", PROXY_CONTACT=").append(PROXY_CONTACT);
        sb.append(", PROXY_POSTCODE=").append(PROXY_POSTCODE);
        sb.append(", FIRSTCENSOR=").append(FIRSTCENSOR);
        sb.append(", FIRSTAUDITDATE=").append(FIRSTAUDITDATE);
        sb.append(", FIRSTMARK=").append(FIRSTMARK);
        sb.append(", FINALCENSOR=").append(FINALCENSOR);
        sb.append(", FINALAUDITDATE=").append(FINALAUDITDATE);
        sb.append(", FINALMARK=").append(FINALMARK);
        sb.append(", STATUS=").append(STATUS);
        sb.append(", CREPERSON=").append(CREPERSON);
        sb.append(", CREDATE=").append(CREDATE);
        sb.append(", CRETIME=").append(CRETIME);
        sb.append(", CREPROID=").append(CREPROID);
        sb.append(", UPDPERSON=").append(UPDPERSON);
        sb.append(", UPDDATE=").append(UPDDATE);
        sb.append(", UPDTIME=").append(UPDTIME);
        sb.append(", UPDPROID=").append(UPDPROID);
        sb.append(", UPDCNT=").append(UPDCNT);
        sb.append("]");
        return sb.toString();
    }
}