package com.bluto.fc.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_ID
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_NAME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PASSWORD
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.LOGIN_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.LOGIN_IP
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.UPDATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.UPDATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_ID
     *
     * @return the value of T_USER.USER_ID
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USER_ID
     *
     * @param userId the value for T_USER.USER_ID
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_NAME
     *
     * @return the value of T_USER.USER_NAME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USER_NAME
     *
     * @param userName the value for T_USER.USER_NAME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PASSWORD
     *
     * @return the value of T_USER.PASSWORD
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PASSWORD
     *
     * @param password the value for T_USER.PASSWORD
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.LOGIN_TIME
     *
     * @return the value of T_USER.LOGIN_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.LOGIN_TIME
     *
     * @param loginTime the value for T_USER.LOGIN_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.LOGIN_IP
     *
     * @return the value of T_USER.LOGIN_IP
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.LOGIN_IP
     *
     * @param loginIp the value for T_USER.LOGIN_IP
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_TIME
     *
     * @return the value of T_USER.CREATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATE_TIME
     *
     * @param createTime the value for T_USER.CREATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_USER
     *
     * @return the value of T_USER.CREATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATE_USER
     *
     * @param createUser the value for T_USER.CREATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.UPDATE_TIME
     *
     * @return the value of T_USER.UPDATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.UPDATE_TIME
     *
     * @param updateTime the value for T_USER.UPDATE_TIME
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.UPDATE_USER
     *
     * @return the value of T_USER.UPDATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.UPDATE_USER
     *
     * @param updateUser the value for T_USER.UPDATE_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Thu May 07 15:53:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}